export const robots = [
    {
      Rank: '1',
      Alias: 'Lucasnm',
      BestLapTime: '37606',
      SubmissionTime: '1698273344829',
      LapCount: '3',
      CollisionCount: '0',
      OffTrackCount: '0',
      SubmissionCount: '1',
    },
    {
        Rank: '2',
        Alias: 'BackloggedCoder#2267',
        BestLapTime: '44198',
        SubmissionTime: '1698282381394',
        LapCount: '3',
        CollisionCount: '0',
        OffTrackCount: '13',
        SubmissionCount: '1',
      },
      {
        Rank: '3',
        Alias: 'MauroSangalli',
        BestLapTime: '50277',
        SubmissionTime: '1698273335875',
        LapCount: '3',
        CollisionCount: '0',
        OffTrackCount: '19',
        SubmissionCount: '3',
      },
      {
        Rank: '4',
        Alias: 'AntoGacetua',
        BestLapTime: '71800',
        SubmissionTime: '1698269035415',
        LapCount: '3',
        CollisionCount: '0',
        OffTrackCount: '1',
        SubmissionCount: '2',
      },
];