name: Test Cypress
on: [push]
jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.4
  #     - name: Cypress.io
  #       uses: cypress-io/github-action@v4.1.0
  #       with:
  #         start: npm start
  deploy-to-aws:
    # needs: cypress-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Sync directory to S3
      uses: aws-actions/amazon-s3-sync-action@v0.3.0
      with:
        path: ./build
        bucket: ${{ secrets.AWS_S3_BUCKET }}
      env:
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
